apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 545009838510.dkr.ecr.us-east-1.amazonaws.com/front
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://3.90.112.31:30008/"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
      protocol: TCP
  selector:
    app: frontend  # Ensure this matches the labels in the Deployment
  type: NodePort
